# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31224e0156697af04b20f8a94024f7a53e580174c8d2c365186b014e883f5d282cac08627c6b36cd3083598e246b81d2bc850a46815949a11260f9a845c7981b

test:
  secret_key_base: c83abd0bfc1c511f2540493215a14d5ccadcbca5fb2ec1838867b68e784554a3bec5f1423b607c2b1f0ef2178fc24d561dcff4fe38ff2ca9baef90831b2e0d1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
